sudo: required

language: ruby
cache: bundler

services:
  - docker

before_install:
  - docker build -t tests-runner:$TRAVIS_COMMIT .

script:
  - docker run --rm tests-runner:$TRAVIS_COMMIT rake test
  - docker run --rm tests-runner:$TRAVIS_COMMIT rubocop -c /app/.rubocop.yml
